name: Trend Mining Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * MON'  # ogni lunedì alle 08:00 UTC (10:00 Roma)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install notion-client beautifulsoup4 requests
    - name: Run Trend Mining
      env:
        NOTION_TOKEN: ${{ secrets.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 }}
        NOTION_DB_ID: ${{ secrets.1f3a908a809f80c3a9acfe3ed6e0cee9?v=1f3a908a809f81fc8470000c224ca709&pvs=4 }}
      run: python trend_mining.py
